#|
 This file is a part of cl-soundio
 (c) 2016 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:cl-user)
(defpackage #:cl-soundio-cffi
  (:nicknames #:org.shirakumo.fraf.soundio.cffi)
  (:use #:cl #:cffi)
  ;; low-level.lisp
  (:export
   #:*static*
   #:libsoundio
   
   #:soundio-error
   #:soundio-error-none
   #:soundio-error-no-mem
   #:soundio-error-init-audio-backend
   #:soundio-error-system-resources
   #:soundio-error-opening-device
   #:soundio-error-no-such-device
   #:soundio-error-invalid
   #:soundio-error-backend-unavailable
   #:soundio-error-streaming
   #:soundio-error-incompatible-device
   #:soundio-error-no-such-client
   #:soundio-error-incompatible-backend
   #:soundio-error-backend-disconnected
   #:soundio-error-interrupted
   #:soundio-error-underflow
   #:soundio-error-encoding-string

   #:soundio-channel-id
   #:soundio-channel-id-invalid
   #:soundio-channel-id-front-left
   #:soundio-channel-id-front-right
   #:soundio-channel-id-front-center
   #:soundio-channel-id-lfe
   #:soundio-channel-id-back-left
   #:soundio-channel-id-back-right
   #:soundio-channel-id-front-left-center
   #:soundio-channel-id-front-right-center
   #:soundio-channel-id-back-center
   #:soundio-channel-id-side-left
   #:soundio-channel-id-side-right
   #:soundio-channel-id-top-center
   #:soundio-channel-id-top-front-left
   #:soundio-channel-id-top-front-center
   #:soundio-channel-id-top-front-right
   #:soundio-channel-id-top-back-left
   #:soundio-channel-id-top-back-center
   #:soundio-channel-id-top-back-right
   #:soundio-channel-id-back-left-center
   #:soundio-channel-id-back-right-center
   #:soundio-channel-id-front-left-wide
   #:soundio-channel-id-front-right-wide
   #:soundio-channel-id-front-left-high
   #:soundio-channel-id-front-center-high
   #:soundio-channel-id-front-right-high
   #:soundio-channel-id-top-front-left-center
   #:soundio-channel-id-top-front-right-center
   #:soundio-channel-id-top-side-left
   #:soundio-channel-id-top-side-right
   #:soundio-channel-id-left-lfe
   #:soundio-channel-id-right-lfe
   #:soundio-channel-id-lfe2
   #:soundio-channel-id-bottom-center
   #:soundio-channel-id-bottom-left-center
   #:soundio-channel-id-bottom-right-center
   #:soundio-channel-id-ms-mid
   #:soundio-channel-id-ms-side
   #:soundio-channel-id-ambisonic-w
   #:soundio-channel-id-ambisonic-x
   #:soundio-channel-id-ambisonic-y
   #:soundio-channel-id-ambisonic-z
   #:soundio-channel-id-xy-x
   #:soundio-channel-id-xy-y
   #:soundio-channel-id-headphones-left
   #:soundio-channel-id-headphones-right
   #:soundio-channel-id-click-track
   #:soundio-channel-id-foreign-language
   #:soundio-channel-id-hearing-impaired
   #:soundio-channel-id-narration
   #:soundio-channel-id-haptic
   #:soundio-channel-id-dialog-centric-mix
   #:soundio-channel-id-aux
   #:soundio-channel-id-aux0
   #:soundio-channel-id-aux1
   #:soundio-channel-id-aux2
   #:soundio-channel-id-aux3
   #:soundio-channel-id-aux4
   #:soundio-channel-id-aux5
   #:soundio-channel-id-aux6
   #:soundio-channel-id-aux7
   #:soundio-channel-id-aux8
   #:soundio-channel-id-aux9
   #:soundio-channel-id-aux10
   #:soundio-channel-id-aux11
   #:soundio-channel-id-aux12
   #:soundio-channel-id-aux13
   #:soundio-channel-id-aux14
   #:soundio-channel-id-aux15

   #:soundio-channel-layout-id
   #:soundio-channel-layout-id-mono
   #:soundio-channel-layout-id-stereo
   #:soundio-channel-layout-id2-point1
   #:soundio-channel-layout-id3-point0
   #:soundio-channel-layout-id3-point0-back
   #:soundio-channel-layout-id3-point1
   #:soundio-channel-layout-id4-point0
   #:soundio-channel-layout-id-quad
   #:soundio-channel-layout-id-quad-side
   #:soundio-channel-layout-id4-point1
   #:soundio-channel-layout-id5-point0-back
   #:soundio-channel-layout-id5-point0-side
   #:soundio-channel-layout-id5-point1
   #:soundio-channel-layout-id5-point1-back
   #:soundio-channel-layout-id6-point0-side
   #:soundio-channel-layout-id6-point0-front
   #:soundio-channel-layout-id-hexagonal
   #:soundio-channel-layout-id6-point1
   #:soundio-channel-layout-id6-point1-back
   #:soundio-channel-layout-id6-point1-front
   #:soundio-channel-layout-id7-point0
   #:soundio-channel-layout-id7-point0-front
   #:soundio-channel-layout-id7-point1
   #:soundio-channel-layout-id7-point1-wide
   #:soundio-channel-layout-id7-point1-wide-back
   #:soundio-channel-layout-id-octagonal

   #:soundio-backend
   #:soundio-backend-none
   #:soundio-backend-jack
   #:soundio-backend-pulse-audio
   #:soundio-backend-alsa
   #:soundio-backend-core-audio
   #:soundio-backend-wasapi
   #:soundio-backend-dummy

   #:soundio-device-aim
   #:soundio-device-aim-input 
   #:soundio-device-aim-output

   #:soundio-format
   #:soundio-format-invalid
   #:soundio-format-s8       
   #:soundio-format-u8       
   #:soundio-format-s16-le    
   #:soundio-format-s16-be    
   #:soundio-format-u16-le    
   #:soundio-format-u16-be    
   #:soundio-format-s24-le    
   #:soundio-format-s24-be    
   #:soundio-format-u24-le    
   #:soundio-format-u24-be    
   #:soundio-format-s32-le    
   #:soundio-format-s32-be    
   #:soundio-format-u32-le    
   #:soundio-format-u32-be    
   #:soundio-format-float32-le
   #:soundio-format-float32-be
   #:soundio-format-float64-le
   #:soundio-format-float64-be

   #:soundio-max-channels

   #:channel-layout
   #:channel-layout-name
   #:channel-layout-channel-count
   #:channel-layout-channels

   #:sample-rate-change
   #:sample-rate-change-min
   #:sample-rate-change-max

   #:channel-area
   #:channel-area-ptr
   #:channel-area-step

   #:soundio
   #:soundio-userdata
   #:soundio-on-devices-change
   #:soundio-on-backend-disconnect
   #:soundio-on-events-signal
   #:soundio-current-backend
   #:soundio-app-name
   #:soundio-emit-rtprio-warning
   #:soundio-jack-info-callback
   #:soundio-jack-error-callback

   #:device
   #:device-soundio
   #:device-id
   #:device-name
   #:device-aim
   #:device-layouts
   #:device-layout-count
   #:device-current-layout
   #:device-formats
   #:device-format-count
   #:device-current-format
   #:device-sample-rates
   #:device-sample-rate-count
   #:device-sample-rate-current
   #:device-software-latency-min
   #:device-software-latency-max
   #:device-software-latency-current
   #:device-is-raw
   #:device-ref-count
   #:device-probe-error

   #:out-stream
   #:out-stream-device
   #:out-stream-format
   #:out-stream-sample-rate
   #:out-stream-layout
   #:out-stream-software-latency
   #:out-stream-userdata
   #:out-stream-write-callback
   #:out-stream-underflow-callback
   #:out-stream-error-callback
   #:out-stream-name
   #:out-stream-non-terminal-hint
   #:out-stream-bytes-per-frame
   #:out-stream-bytes-per-sample
   #:out-stream-layout-error

   #:in-stream
   #:in-stream-device
   #:in-stream-format
   #:in-stream-sample-rate
   #:in-stream-layout
   #:in-stream-software-latency
   #:in-stream-userdata
   #:in-stream-read-callback
   #:in-stream-overflow-callback
   #:in-stream-error-callback
   #:in-stream-name
   #:in-stream-non-terminal-hint
   #:in-stream-bytes-per-frame
   #:in-stream-bytes-per-sample
   #:in-stream-layout-error

   #:ring-buffer

   #:define-callback-func

   #:soundio-version-string
   #:soundio-version-major
   #:soundio-version-minor
   #:soundio-version-patch
   #:soundio-create
   #:soundio-destroy
   #:soundio-connect
   #:soundio-connect-backend
   #:soundio-disconnect
   #:soundio-strerror
   #:soundio-backend-name
   #:soundio-backend-count
   #:soundio-get-backend
   #:soundio-have-backend
   #:soundio-flush-events
   #:soundio-wait-events
   #:soundio-wakeup
   #:soundio-force-device-scan
   #:soundio-channel-layout-equal
   #:soundio-get-channel-name
   #:soundio-parse-channel-id
   #:soundio-channel-layout-builtin-count
   #:soundio-channel-layout-get-builtin
   #:soundio-channel-layout-get-default
   #:soundio-channel-layout-find-channel
   #:soundio-channel-layout-detect-builtin
   #:soundio-best-matching-channel-layout
   #:soundio-sort-channel-layouts
   #:soundio-get-bytes-per-sample
   #:soundio-format-string
   #:soundio-input-device-count
   #:soundio-output-device-count
   #:soundio-get-input-device
   #:soundio-get-output-device
   #:soundio-default-input-device-index
   #:soundio-default-output-device-index
   #:soundio-device-ref
   #:soundio-device-unref
   #:soundio-device-equal
   #:soundio-device-sort-channel-layouts
   #:soundio-device-supports-format
   #:soundio-device-supports-layout
   #:soundio-device-supports-sample-rate
   #:soundio-device-nearest-sample-rate
   #:soundio-outstream-create
   #:soundio-outstream-destroy
   #:soundio-outstream-open
   #:soundio-outstream-start
   #:soundio-outstream-begin-write
   #:soundio-outstream-end-write
   #:soundio-outstream-clear-buffer
   #:soundio-outstream-pause
   #:soundio-outstream-get-latency
   #:soundio-instream-create
   #:soundio-instream-destroy
   #:soundio-instream-open
   #:soundio-instream-start
   #:soundio-instream-begin-read
   #:soundio-instream-end-read
   #:soundio-instream-pause
   #:soundio-instream-get-latency
   #:soundio-ring-buffer-create
   #:soundio-ring-buffer-destroy
   #:soundio-ring-buffer-capacity
   #:soundio-ring-buffer-write-ptr
   #:soundio-ring-buffer-advance-write-ptr
   #:soundio-ring-buffer-read-ptr
   #:soundio-ring-buffer-advance-read-ptr
   #:soundio-ring-buffer-fill-count
   #:soundio-ring-buffer-free-count
   #:soundio-ring-buffer-clear
   #:soundio-get-bytes-per-frame
   #:soundio-get-bytes-per-second))

(defpackage #:cl-soundio
  (:nicknames #:org.shirakumo.fraf.soundio)
  (:use #:cl #:org.shirakumo.fraf.soundio.cffi)
  ;; wrapper.lisp
  (:export
   ))
