#|
 This file is a part of cl-soundio
 (c) 2016 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:cl-user)
(defpackage #:cl-soundio-cffi
  (:nicknames #:org.shirakumo.fraf.soundio.cffi)
  (:use #:cl #:cffi)
  ;; low-level.lisp
  (:export
   #:*static*
   #:libsoundio
   
   #:soundio-error
   #:error-none
   #:error-no-mem
   #:error-init-audio-backend
   #:error-system-resources
   #:error-opening-device
   #:error-no-such-device
   #:error-invalid
   #:error-backend-unavailable
   #:error-streaming
   #:error-incompatible-device
   #:error-no-such-client
   #:error-incompatible-backend
   #:error-backend-disconnected
   #:error-interrupted
   #:error-underflow
   #:error-encoding-string

   #:channel-id
   #:channel-id-invalid
   #:channel-id-front-left
   #:channel-id-front-right
   #:channel-id-front-center
   #:channel-id-lfe
   #:channel-id-back-left
   #:channel-id-back-right
   #:channel-id-front-left-center
   #:channel-id-front-right-center
   #:channel-id-back-center
   #:channel-id-side-left
   #:channel-id-side-right
   #:channel-id-top-center
   #:channel-id-top-front-left
   #:channel-id-top-front-center
   #:channel-id-top-front-right
   #:channel-id-top-back-left
   #:channel-id-top-back-center
   #:channel-id-top-back-right
   #:channel-id-back-left-center
   #:channel-id-back-right-center
   #:channel-id-front-left-wide
   #:channel-id-front-right-wide
   #:channel-id-front-left-high
   #:channel-id-front-center-high
   #:channel-id-front-right-high
   #:channel-id-top-front-left-center
   #:channel-id-top-front-right-center
   #:channel-id-top-side-left
   #:channel-id-top-side-right
   #:channel-id-left-lfe
   #:channel-id-right-lfe
   #:channel-id-lfe2
   #:channel-id-bottom-center
   #:channel-id-bottom-left-center
   #:channel-id-bottom-right-center
   #:channel-id-ms-mid
   #:channel-id-ms-side
   #:channel-id-ambisonic-w
   #:channel-id-ambisonic-x
   #:channel-id-ambisonic-y
   #:channel-id-ambisonic-z
   #:channel-id-xy-x
   #:channel-id-xy-y
   #:channel-id-headphones-left
   #:channel-id-headphones-right
   #:channel-id-click-track
   #:channel-id-foreign-language
   #:channel-id-hearing-impaired
   #:channel-id-narration
   #:channel-id-haptic
   #:channel-id-dialog-centric-mix
   #:channel-id-aux
   #:channel-id-aux0
   #:channel-id-aux1
   #:channel-id-aux2
   #:channel-id-aux3
   #:channel-id-aux4
   #:channel-id-aux5
   #:channel-id-aux6
   #:channel-id-aux7
   #:channel-id-aux8
   #:channel-id-aux9
   #:channel-id-aux10
   #:channel-id-aux11
   #:channel-id-aux12
   #:channel-id-aux13
   #:channel-id-aux14
   #:channel-id-aux15

   #:channel-layout-id
   #:channel-layout-id-mono
   #:channel-layout-id-stereo
   #:channel-layout-id2-point1
   #:channel-layout-id3-point0
   #:channel-layout-id3-point0-back
   #:channel-layout-id3-point1
   #:channel-layout-id4-point0
   #:channel-layout-id-quad
   #:channel-layout-id-quad-side
   #:channel-layout-id4-point1
   #:channel-layout-id5-point0-back
   #:channel-layout-id5-point0-side
   #:channel-layout-id5-point1
   #:channel-layout-id5-point1-back
   #:channel-layout-id6-point0-side
   #:channel-layout-id6-point0-front
   #:channel-layout-id-hexagonal
   #:channel-layout-id6-point1
   #:channel-layout-id6-point1-back
   #:channel-layout-id6-point1-front
   #:channel-layout-id7-point0
   #:channel-layout-id7-point0-front
   #:channel-layout-id7-point1
   #:channel-layout-id7-point1-wide
   #:channel-layout-id7-point1-wide-back
   #:channel-layout-id-octagonal

   #:backend
   #:backend-none
   #:backend-jack
   #:backend-pulse-audio
   #:backend-alsa
   #:backend-core-audio
   #:backend-wasapi
   #:backend-dummy

   #:device-aim
   #:device-aim-input 
   #:device-aim-output

   #:format
   #:format-invalid
   #:format-s8       
   #:format-u8       
   #:format-s16-le    
   #:format-s16-be    
   #:format-u16-le    
   #:format-u16-be    
   #:format-s24-le    
   #:format-s24-be    
   #:format-u24-le    
   #:format-u24-be    
   #:format-s32-le    
   #:format-s32-be    
   #:format-u32-le    
   #:format-u32-be    
   #:format-float32-le
   #:format-float32-be
   #:format-float64-le
   #:format-float64-be

   #:max-channels

   #:channel-layout
   #:channel-layout-name
   #:channel-layout-channel-count
   #:channel-layout-channels

   #:sample-rate-change
   #:sample-rate-change-min
   #:sample-rate-change-max

   #:channel-area
   #:channel-area-ptr
   #:channel-area-step

   #:soundio
   #:soundio-userdata
   #:soundio-on-devices-change
   #:soundio-on-backend-disconnect
   #:soundio-on-events-signal
   #:soundio-current-backend
   #:soundio-app-name
   #:soundio-emit-rtprio-warning
   #:soundio-jack-info-callback
   #:soundio-jack-error-callback

   #:device
   #:device-soundio
   #:device-id
   #:device-name
   #:device-aim
   #:device-layouts
   #:device-layout-count
   #:device-current-layout
   #:device-formats
   #:device-format-count
   #:device-current-format
   #:device-sample-rates
   #:device-sample-rate-count
   #:device-sample-rate-current
   #:device-software-latency-min
   #:device-software-latency-max
   #:device-software-latency-current
   #:device-is-raw
   #:device-ref-count
   #:device-probe-error

   #:out-stream
   #:out-stream-device
   #:out-stream-format
   #:out-stream-sample-rate
   #:out-stream-layout
   #:out-stream-software-latency
   #:out-stream-userdata
   #:out-stream-write-callback
   #:out-stream-underflow-callback
   #:out-stream-error-callback
   #:out-stream-name
   #:out-stream-non-terminal-hint
   #:out-stream-bytes-per-frame
   #:out-stream-bytes-per-sample
   #:out-stream-layout-error

   #:in-stream
   #:in-stream-device
   #:in-stream-format
   #:in-stream-sample-rate
   #:in-stream-layout
   #:in-stream-software-latency
   #:in-stream-userdata
   #:in-stream-read-callback
   #:in-stream-overflow-callback
   #:in-stream-error-callback
   #:in-stream-name
   #:in-stream-non-terminal-hint
   #:in-stream-bytes-per-frame
   #:in-stream-bytes-per-sample
   #:in-stream-layout-error

   #:ring-buffer

   #:define-callback-func

   #:version-string
   #:version-major
   #:version-minor
   #:version-patch
   #:create
   #:destroy
   #:connect
   #:connect-backend
   #:disconnect
   #:strerror
   #:backend-name
   #:backend-count
   #:get-backend
   #:have-backend
   #:flush-events
   #:wait-events
   #:wakeup
   #:force-device-scan
   #:channel-layout-equal
   #:get-channel-name
   #:parse-channel-id
   #:channel-layout-builtin-count
   #:channel-layout-get-builtin
   #:channel-layout-get-default
   #:channel-layout-find-channel
   #:channel-layout-detect-builtin
   #:best-matching-channel-layout
   #:sort-channel-layouts
   #:get-bytes-per-sample
   #:format-string
   #:input-device-count
   #:output-device-count
   #:get-input-device
   #:get-output-device
   #:default-input-device-index
   #:default-output-device-index
   #:device-ref
   #:device-unref
   #:device-equal
   #:device-sort-channel-layouts
   #:device-supports-format
   #:device-supports-layout
   #:device-supports-sample-rate
   #:device-nearest-sample-rate
   #:outstream-create
   #:outstream-destroy
   #:outstream-open
   #:outstream-start
   #:outstream-begin-write
   #:outstream-end-write
   #:outstream-clear-buffer
   #:outstream-pause
   #:outstream-get-latency
   #:instream-create
   #:instream-destroy
   #:instream-open
   #:instream-start
   #:instream-begin-read
   #:instream-end-read
   #:instream-pause
   #:instream-get-latency
   #:ring-buffer-create
   #:ring-buffer-destroy
   #:ring-buffer-capacity
   #:ring-buffer-write-ptr
   #:ring-buffer-advance-write-ptr
   #:ring-buffer-read-ptr
   #:ring-buffer-advance-read-ptr
   #:ring-buffer-fill-count
   #:ring-buffer-free-count
   #:ring-buffer-clear
   #:get-bytes-per-frame
   #:get-bytes-per-second))

(defpackage #:cl-soundio
  (:nicknames #:org.shirakumo.fraf.soundio)
  (:use #:cl #:org.shirakumo.fraf.soundio.cffi)
  ;; wrapper.lisp
  (:export
   ))
